[workspace]
members = [
    "nodes/node-template",
    "nodes/tomasz-node",
    "pallets/pallete-template",
    "pallets/hello-substrate",
    "pallets/adding-machine",
    "runtimes/runtime-template",
    "runtimes/tomasz-runtime",
]
[profile.release]
panic = "unwind"
