[workspace]
members = [
    "nodes/node-template",
    "nodes/tomasz-node",
    "pallets/template",
    "pallets/hello-substrate",
    "pallets/single-value-storage",
    "runtimes/runtime-template",
    "runtimes/tomasz-runtime",
]
[profile.release]
panic = "unwind"
